#!/bin/sh

# Fix up glifs in files touched by FontForge and normalize
psffixffglifs source/masters/KayPhoDu-Regular.ufo -p checkfix=fix
psffixffglifs source/masters/KayPhoDu-Bold.ufo -p checkfix=fix

./preflight
