#!/bin/sh

# Fix up glifs in files touched by FontForge and normalize
psffixffglifs source/masters/KayPhoDuMaster-Regular.ufo -p checkfix=fix
psffixffglifs source/masters/KayPhoDuMaster-Bold.ufo -p checkfix=fix

./preflight
