#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/masters/KayPhoDuMaster-Regular.ufo &
psfnormalize -p checkfix=fix source/masters/KayPhoDuMaster-Bold.ufo &
wait

# Update glyph order in Regular UFO
psfsetglyphorder --header sort_design -i source/glyph_data.csv source/masters/KayPhoDuMaster-Regular.ufo

# Update production names in Regular UFO
psfsetpsnames -i source/glyph_data.csv source/masters/KayPhoDuMaster-Regular.ufo

# Following sync will copy psnames and glyphorder updates to all fonts
psfsyncmasters source/KayPhoDu.designspace
